### ISSUE TITLE
Component tab view update

### ISSUE THREAD

**Issue by roaming97** [infraregistry/app#19]
The tabs in components don't update when changing to another route, causing possible route recursion issues, should also help to prevent selecting the same section when already in it (for example not being able to choose `Dependencies` when the sub-route is already `/dependencies`).

![Image](https://github.com/user-attachments/assets/f508f7b3-bf00-4c12-a66e-6793622aa4f5)

**Tasks for this issue**
- [X] Update tab state accordingly
- [X] Prevent selection of current component settings section
- [X] Fix route recursion when selecting a button
